---
- name: Aktualisiere Ubuntu-Systeme
  hosts: all
  become: yes
  tasks:
    - name: Aktualisiere die Paketliste
      apt:
        update_cache: yes
      tags: update

    - name: FÃ¼hre das Systemupgrade durch
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: upgrade
